config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :states
  resources :services
  resources :buildings
  resources :clients
  devise_for :users
  get 'homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "homes#index"
end

app/models/service.rb
class Service < ApplicationRecord
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show edit update destroy ]

  # GET /services or /services.json
  def index
    @services = Service.all
  end

  # GET /services/1 or /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services or /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to service_url(@service), notice: "Service was successfully created." }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1 or /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to service_url(@service), notice: "Service was successfully updated." }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1 or /services/1.json
  def destroy
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url, notice: "Service was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:pool, :barbecue, :gym, :green_areas, :childish_games, :parking_lots, :pet_friendly)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_with(model: service) do |form| %>
  <% if service.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :pool, style: "display: block" %>
    <%= form.text_field :pool %>
  </div>

  <div>
    <%= form.label :barbecue, style: "display: block" %>
    <%= form.text_field :barbecue %>
  </div>

  <div>
    <%= form.label :gym, style: "display: block" %>
    <%= form.text_field :gym %>
  </div>

  <div>
    <%= form.label :green_areas, style: "display: block" %>
    <%= form.text_field :green_areas %>
  </div>

  <div>
    <%= form.label :childish_games, style: "display: block" %>
    <%= form.text_field :childish_games %>
  </div>

  <div>
    <%= form.label :parking_lots, style: "display: block" %>
    <%= form.text_field :parking_lots %>
  </div>

  <div>
    <%= form.label :pet_friendly, style: "display: block" %>
    <%= form.text_field :pet_friendly %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/services/_service.html.erb
<div id="<%= dom_id service %>">
  <p>
    <strong>Pool:</strong>
    <%= service.pool %>
  </p>

  <p>
    <strong>Barbecue:</strong>
    <%= service.barbecue %>
  </p>

  <p>
    <strong>Gym:</strong>
    <%= service.gym %>
  </p>

  <p>
    <strong>Green areas:</strong>
    <%= service.green_areas %>
  </p>

  <p>
    <strong>Childish games:</strong>
    <%= service.childish_games %>
  </p>

  <p>
    <strong>Parking lots:</strong>
    <%= service.parking_lots %>
  </p>

  <p>
    <strong>Pet friendly:</strong>
    <%= service.pet_friendly %>
  </p>

</div>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render "form", service: @service %>

<br>

<div>
  <%= link_to "Show this service", @service %> |
  <%= link_to "Back to services", services_path %>
</div>

app/views/services/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Services</h1>

<div id="services">
  <% @services.each do |service| %>
    <%= render service %>
    <p>
      <%= link_to "Show this service", service %>
    </p>
  <% end %>
</div>

<%= link_to "New service", new_service_path %>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render "form", service: @service %>

<br>

<div>
  <%= link_to "Back to services", services_path %>
</div>

app/views/services/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @service %>

<div>
  <%= link_to "Edit this service", edit_service_path(@service) %> |
  <%= link_to "Back to services", services_path %>

  <%= button_to "Destroy this service", @service, method: :delete %>
</div>