config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :states
  resources :services
  resources :buildings
  resources :clients
  devise_for :users
  get 'homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "homes#index"
end

app/models/state.rb
class State < ApplicationRecord
    has_many :departments
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: %i[ show edit update destroy ]

  # GET /states or /states.json
  def index
    @states = State.all
  end

  # GET /states/1 or /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states or /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to state_url(@state), notice: "State was successfully created." }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1 or /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to state_url(@state), notice: "State was successfully updated." }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1 or /states/1.json
  def destroy
    @state.destroy

    respond_to do |format|
      format.html { redirect_to states_url, notice: "State was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def state_params
      params.require(:state).permit(:available, :rent, :sale, :leased, :sold)
    end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<%= form_with(model: state) do |form| %>
  <% if state.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
        <% state.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :available, style: "display: block" %>
    <%= form.text_field :available %>
  </div>

  <div>
    <%= form.label :rent, style: "display: block" %>
    <%= form.text_field :rent %>
  </div>

  <div>
    <%= form.label :sale, style: "display: block" %>
    <%= form.text_field :sale %>
  </div>

  <div>
    <%= form.label :leased, style: "display: block" %>
    <%= form.text_field :leased %>
  </div>

  <div>
    <%= form.label :sold, style: "display: block" %>
    <%= form.text_field :sold %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/states/_state.html.erb
<div id="<%= dom_id state %>">
  <p>
    <strong>Available:</strong>
    <%= state.available %>
  </p>

  <p>
    <strong>Rent:</strong>
    <%= state.rent %>
  </p>

  <p>
    <strong>Sale:</strong>
    <%= state.sale %>
  </p>

  <p>
    <strong>Leased:</strong>
    <%= state.leased %>
  </p>

  <p>
    <strong>Sold:</strong>
    <%= state.sold %>
  </p>

</div>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Show this state", @state %> |
  <%= link_to "Back to states", states_path %>
</div>

app/views/states/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>States</h1>

<div id="states">
  <% @states.each do |state| %>
    <%= render state %>
    <p>
      <%= link_to "Show this state", state %>
    </p>
  <% end %>
</div>

<%= link_to "New state", new_state_path %>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render "form", state: @state %>

<br>

<div>
  <%= link_to "Back to states", states_path %>
</div>

app/views/states/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @state %>

<div>
  <%= link_to "Edit this state", edit_state_path(@state) %> |
  <%= link_to "Back to states", states_path %>

  <%= button_to "Destroy this state", @state, method: :delete %>
</div>