config/routes.rb
Rails.application.routes.draw do
  resources :departments
  resources :states
  resources :services
  resources :buildings
  resources :clients
  devise_for :users
  get 'homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "homes#index"
end

app/models/building.rb
class Building < ApplicationRecord
    has_and_belongs_to_many :additional
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: %i[ show edit update destroy ]

  # GET /buildings or /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1 or /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings or /buildings.json
  def create
    @building = Building.new(building_params)

    respond_to do |format|
      if @building.save
        format.html { redirect_to building_url(@building), notice: "Building was successfully created." }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buildings/1 or /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to building_url(@building), notice: "Building was successfully updated." }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1 or /buildings/1.json
  def destroy
    @building.destroy

    respond_to do |format|
      format.html { redirect_to buildings_url, notice: "Building was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def building_params
      params.require(:building).permit(:name, :street, :number, :city, :commune)
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_building.html.erb
<div id="<%= dom_id building %>">
  <p>
    <strong>Name:</strong>
    <%= building.name %>
  </p>

  <p>
    <strong>Street:</strong>
    <%= building.street %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= building.number %>
  </p>

  <p>
    <strong>City:</strong>
    <%= building.city %>
  </p>

  <p>
    <strong>Commune:</strong>
    <%= building.commune %>
  </p>

</div>

app/views/buildings/_form.html.erb
<%= form_with(model: building) do |form| %>
  <% if building.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
        <% building.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :street, style: "display: block" %>
    <%= form.text_field :street %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.text_field :number %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :commune, style: "display: block" %>
    <%= form.text_field :commune %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing building</h1>

<%= render "form", building: @building %>

<br>

<div>
  <%= link_to "Show this building", @building %> |
  <%= link_to "Back to buildings", buildings_path %>
</div>

app/views/buildings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Buildings</h1>

<div id="buildings">
  <% @buildings.each do |building| %>
    <%= render building %>
    <p>
      <%= link_to "Show this building", building %>
    </p>
  <% end %>
</div>

<%= link_to "New building", new_building_path %>

app/views/buildings/new.html.erb
<h1>New building</h1>

<%= render "form", building: @building %>

<br>

<div>
  <%= link_to "Back to buildings", buildings_path %>
</div>

app/views/buildings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @building %>

<div>
  <%= link_to "Edit this building", edit_building_path(@building) %> |
  <%= link_to "Back to buildings", buildings_path %>

  <%= button_to "Destroy this building", @building, method: :delete %>
</div>